jush.tr.http = { _0: /$/ };

jush.slugs.http = function (name) { return name.replace(/^(\d{3})\b.*/, '$1'); }; // status code links use only the number

jush.build_links2('http', 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/$key', /(^(?:HTTP\/[0-9.]+\s+)?)/, /(:|$|(?= ))/gim, {
	'Status/$1': /(\d{3}\b.*)/,
	'Methods/$1': /(CONNECT|DELETE|GET|HEAD|OPTIONS|PATCH|POST|PUT|TRACE)/,
	'Headers/$1': /(Accept|Accept-CH|Accept-Encoding|Accept-Language|Accept-Patch|Accept-Post|Accept-Ranges|Access-Control-Allow-Credentials|Access-Control-Allow-Headers|Access-Control-Allow-Methods|Access-Control-Allow-Origin|Access-Control-Expose-Headers|Access-Control-Max-Age|Access-Control-Request-Headers|Access-Control-Request-Method|Activate-Storage-Access|Age|Allow|Alt-Svc|Alt-Used|Attribution-Reporting-Eligible|Attribution-Reporting-Register-Source|Attribution-Reporting-Register-Trigger|Authorization|Available-Dictionary|Cache-Control|Clear-Site-Data|Connection|Content-DPR|Content-Digest|Content-Disposition|Content-Encoding|Content-Language|Content-Length|Content-Location|Content-Range|Content-Security-Policy|Content-Security-Policy-Report-Only|Content-Type|Cookie|Critical-CH|Cross-Origin-Embedder-Policy|Cross-Origin-Embedder-Policy-Report-Only|Cross-Origin-Opener-Policy|Cross-Origin-Resource-Policy|DNT|DPR|Date|Device-Memory|Dictionary-ID|Downlink|ECT|ETag|Early-Data|Expect|Expect-CT|Expires|Forwarded|From|Host|Idempotency-Key|If-Match|If-Modified-Since|If-None-Match|If-Range|If-Unmodified-Since|Integrity-Policy|Integrity-Policy-Report-Only|Keep-Alive|Last-Modified|Link|Location|Max-Forwards|NEL|No-Vary-Search|Observe-Browsing-Topics|Origin|Origin-Agent-Cluster|Permissions-Policy|Permissions-Policy-Report-Only|Pragma|Prefer|Preference-Applied|Priority|Proxy-Authenticate|Proxy-Authorization|RTT|Range|Referer|Referrer-Policy|Refresh|Report-To|Reporting-Endpoints|Repr-Digest|Retry-After|Save-Data|Sec-Browsing-Topics|Sec-CH-DPR|Sec-CH-Device-Memory|Sec-CH-Prefers-Color-Scheme|Sec-CH-Prefers-Reduced-Motion|Sec-CH-Prefers-Reduced-Transparency|Sec-CH-UA|Sec-CH-UA-Arch|Sec-CH-UA-Bitness|Sec-CH-UA-Form-Factors|Sec-CH-UA-Full-Version|Sec-CH-UA-Full-Version-List|Sec-CH-UA-Mobile|Sec-CH-UA-Model|Sec-CH-UA-Platform|Sec-CH-UA-Platform-Version|Sec-CH-UA-WoW64|Sec-CH-Viewport-Height|Sec-CH-Viewport-Width|Sec-CH-Width|Sec-Fetch-Dest|Sec-Fetch-Mode|Sec-Fetch-Site|Sec-Fetch-Storage-Access|Sec-Fetch-User|Sec-GPC|Sec-Private-State-Token|Sec-Private-State-Token-Crypto-Version|Sec-Private-State-Token-Lifetime|Sec-Purpose|Sec-Redemption-Record|Sec-Speculation-Tags|Sec-WebSocket-Accept|Sec-WebSocket-Extensions|Sec-WebSocket-Key|Sec-WebSocket-Protocol|Sec-WebSocket-Version|Server|Server-Timing|Service-Worker|Service-Worker-Allowed|Service-Worker-Navigation-Preload|Set-Cookie|Set-Login|SourceMap|Speculation-Rules|Strict-Transport-Security|Supports-Loading-Mode|TE|Timing-Allow-Origin|Tk|Trailer|Transfer-Encoding|Upgrade|Upgrade-Insecure-Requests|Use-As-Dictionary|User-Agent|Vary|Via|Viewport-Width|WWW-Authenticate|Want-Content-Digest|Want-Repr-Digest|Warning|Width|X-Content-Type-Options|X-DNS-Prefetch-Control|X-Forwarded-For|X-Forwarded-Host|X-Forwarded-Proto|X-Frame-Options|X-Permitted-Cross-Domain-Policies|X-Powered-By|X-Robots-Tag|X-XSS-Protection)/,
});
