jush.tr.oracle = { sqlite_apo: /n?'/i, sqlite_quo: /"/, one: /--/, com: /\/\*/, num: /(?:\b[0-9]+\.?[0-9]*|\.[0-9]+)(?:e[+-]?[0-9]+)?[fd]?/i }; //! q'

jush.autocompleting.sql.push('oracle', 'sqlite_quo'); // sqlite_quo is a quoted identifier

jush.slugs.oracle = name => name.toUpperCase().replace(/\s+/g, '-'); // the pages are named after the construct: ALTER TABLE -> ALTER-TABLE

jush.build_links2('oracle', 'https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/$key', /(\b)/, /(\b)/gi, {
	'$1-Unified-Auditing.html': /(AUDIT|NOAUDIT)/,
	'SET-CONSTRAINTS.html': /(SET\s+CONSTRAINTS?)/,
	'CREATE-ANALYTIC-VIEW.html': /(CREATE(?:\s+OR\s+REPLACE)?(?:\s+FORCE|\s+NOFORCE)?\s+ANALYTIC\s+VIEW)/,
	'CREATE-ATTRIBUTE-DIMENSION.html': /(CREATE(?:\s+OR\s+REPLACE)?(?:\s+FORCE|\s+NOFORCE)?\s+ATTRIBUTE\s+DIMENSION)/,
	'CREATE-HIERARCHY.html': /(CREATE(?:\s+OR\s+REPLACE)?(?:\s+FORCE|\s+NOFORCE)?\s+HIERARCHY)/,
	'CREATE-CONTEXT.html': /(CREATE(?:\s+OR\s+REPLACE)?\s+CONTEXT)/,
	'CREATE-DIRECTORY.html': /(CREATE(?:\s+OR\s+REPLACE)?\s+DIRECTORY)/,
	'CREATE-INDEXTYPE.html': /(CREATE(?:\s+OR\s+REPLACE)?\s+INDEXTYPE)/,
	'CREATE-OPERATOR.html': /(CREATE(?:\s+OR\s+REPLACE)?\s+OPERATOR)/,
	'CREATE-FUNCTION.html': /(CREATE(?:\s+OR\s+REPLACE)?(?:\s+EDITIONABLE|\s+NONEDITIONABLE)?\s+FUNCTION)/,
	'CREATE-LIBRARY.html': /(CREATE(?:\s+OR\s+REPLACE)?(?:\s+EDITIONABLE|\s+NONEDITIONABLE)?\s+LIBRARY)/,
	'CREATE-PACKAGE-BODY.html': /(CREATE(?:\s+OR\s+REPLACE)?(?:\s+EDITIONABLE|\s+NONEDITIONABLE)?\s+PACKAGE\s+BODY)/,
	'CREATE-PACKAGE.html': /(CREATE(?:\s+OR\s+REPLACE)?(?:\s+EDITIONABLE|\s+NONEDITIONABLE)?\s+PACKAGE)/,
	'CREATE-PROCEDURE.html': /(CREATE(?:\s+OR\s+REPLACE)?(?:\s+EDITIONABLE|\s+NONEDITIONABLE)?\s+PROCEDURE)/,
	'CREATE-TRIGGER.html': /(CREATE(?:\s+OR\s+REPLACE)?(?:\s+EDITIONABLE|\s+NONEDITIONABLE)?\s+TRIGGER)/,
	'CREATE-TYPE-BODY.html': /(CREATE(?:\s+OR\s+REPLACE)?(?:\s+EDITIONABLE|\s+NONEDITIONABLE)?\s+TYPE\s+BODY)/,
	'CREATE-TYPE.html': /(CREATE(?:\s+OR\s+REPLACE)?(?:\s+EDITIONABLE|\s+NONEDITIONABLE)?\s+TYPE)/,
	'CREATE-SYNONYM.html': /(CREATE(?:\s+OR\s+REPLACE)?(?:\s+EDITIONABLE|\s+NONEDITIONABLE)?(?:\s+PUBLIC)?\s+SYNONYM)/,
	'CREATE-VIEW.html': /(CREATE(?:\s+OR\s+REPLACE)?(?:\s+FORCE|\s+NO\s+FORCE)?(?:\s+EDITIONABLE\s+EDITIONING|\s+EDITIONABLE|\s+EDITIONING|\s+NONEDITIONABLE)?\s+VIEW)/,
	'CREATE-JAVA.html': /(CREATE(?:\s+OR\s+REPLACE)?(?:\s+AND\s+COMPILE|\s+AND\s+RESOLVE)?(?:\s+NOFORCE)?\s+JAVA)/,
	'CREATE-OUTLINE.html': /(CREATE(?:\s+OR\s+REPLACE)?(?:\s+PRIVATE|\s+PUBLIC)?\s+OUTLINE)/,
	'CREATE-DATABASE-LINK.html': /(CREATE(?:\s+SHARED)?(?:\s+PUBLIC)?\s+DATABASE\s+LINK)/,
	'CREATE-RESTORE-POINT.html': /(CREATE(?:\s+CLEAN)?\s+RESTORE\s+POINT)/,
	'CREATE-ROLLBACK-SEGMENT.html': /(CREATE(?:\s+PUBLIC)?\s+ROLLBACK\s+SEGMENT)/,
	'CREATE-TABLE.html': /(CREATE(?:\s+GLOBAL\s+TEMPORARY|\s+PRIVATE\s+TEMPORARY|\s+SHARDED|\s+DUPLICATED|\s+IMMUTABLE\s+BLOCKCHAIN|\s+BLOCKCHAIN|\s+IMMUTABLE)?\s+TABLE)/,
	'CREATE-INDEX.html': /(CREATE(?:\s+UNIQUE|\s+BITMAP)?\s+INDEX)/,
	'$1.html': /(ADMINISTER\s+KEY\s+MANAGEMENT|ALTER\s+ANALYTIC\s+VIEW|ALTER\s+ATTRIBUTE\s+DIMENSION|ALTER\s+CLUSTER|ALTER\s+DATABASE\s+DICTIONARY|ALTER\s+DATABASE\s+LINK|ALTER\s+DATABASE|ALTER\s+DIMENSION|ALTER\s+DISKGROUP|ALTER\s+FLASHBACK\s+ARCHIVE|ALTER\s+FUNCTION|ALTER\s+HIERARCHY|ALTER\s+INDEX|ALTER\s+INDEXTYPE|ALTER\s+INMEMORY\s+JOIN\s+GROUP|ALTER\s+JAVA|ALTER\s+LIBRARY|ALTER\s+LOCKDOWN\s+PROFILE|ALTER\s+MATERIALIZED\s+VIEW\s+LOG|ALTER\s+MATERIALIZED\s+VIEW|ALTER\s+MATERIALIZED\s+ZONEMAP|ALTER\s+OPERATOR|ALTER\s+OUTLINE|ALTER\s+PACKAGE|ALTER\s+PLUGGABLE\s+DATABASE|ALTER\s+PROCEDURE|ALTER\s+PROFILE|ALTER\s+RESOURCE\s+COST|ALTER\s+ROLE|ALTER\s+ROLLBACK\s+SEGMENT|ALTER\s+SEQUENCE|ALTER\s+SESSION|ALTER\s+SYNONYM|ALTER\s+SYSTEM|ALTER\s+TABLE|ALTER\s+TABLESPACE\s+SET|ALTER\s+TABLESPACE|ALTER\s+TRIGGER|ALTER\s+TYPE|ALTER\s+USER|ALTER\s+VIEW|ANALYZE|ASSOCIATE\s+STATISTICS|CALL|COMMENT|COMMIT|CREATE\s+CLUSTER|CREATE\s+CONTROLFILE|CREATE\s+DATABASE|CREATE\s+DIMENSION|CREATE\s+DISKGROUP|CREATE\s+EDITION|CREATE\s+FLASHBACK\s+ARCHIVE|CREATE\s+INMEMORY\s+JOIN\s+GROUP|CREATE\s+LOCKDOWN\s+PROFILE|CREATE\s+MATERIALIZED\s+VIEW\s+LOG|CREATE\s+MATERIALIZED\s+VIEW|CREATE\s+MATERIALIZED\s+ZONEMAP|CREATE\s+PFILE|CREATE\s+PLUGGABLE\s+DATABASE|CREATE\s+PROFILE|CREATE\s+ROLE|CREATE\s+SCHEMA|CREATE\s+SEQUENCE|CREATE\s+SPFILE|CREATE\s+TABLESPACE\s+SET|CREATE\s+USER|DELETE|DISASSOCIATE\s+STATISTICS|DROP\s+ANALYTIC\s+VIEW|DROP\s+ATTRIBUTE\s+DIMENSION|DROP\s+CLUSTER|DROP\s+CONTEXT|DROP\s+DATABASE\s+LINK|DROP\s+DATABASE|DROP\s+DIMENSION|DROP\s+DIRECTORY|DROP\s+DISKGROUP|DROP\s+EDITION|DROP\s+FLASHBACK\s+ARCHIVE|DROP\s+FUNCTION|DROP\s+HIERARCHY|DROP\s+INDEX|DROP\s+INDEXTYPE|DROP\s+INMEMORY\s+JOIN\s+GROUP|DROP\s+JAVA|DROP\s+LIBRARY|DROP\s+LOCKDOWN\s+PROFILE|DROP\s+MATERIALIZED\s+VIEW\s+LOG|DROP\s+MATERIALIZED\s+VIEW|DROP\s+MATERIALIZED\s+ZONEMAP|DROP\s+OPERATOR|DROP\s+OUTLINE|DROP\s+PACKAGE|DROP\s+PLUGGABLE\s+DATABASE|DROP\s+PROCEDURE|DROP\s+PROFILE|DROP\s+RESTORE\s+POINT|DROP\s+ROLE|DROP\s+ROLLBACK\s+SEGMENT|DROP\s+SEQUENCE|DROP\s+SYNONYM|DROP\s+TABLE|DROP\s+TABLESPACE\s+SET|DROP\s+TABLESPACE|DROP\s+TRIGGER|DROP\s+TYPE\s+BODY|DROP\s+TYPE|DROP\s+USER|DROP\s+VIEW|EXPLAIN\s+PLAN|FLASHBACK\s+DATABASE|FLASHBACK\s+TABLE|GRANT|INSERT|LOCK\s+TABLE|MERGE|PURGE|RENAME|REVOKE|ROLLBACK|SAVEPOINT|SELECT|SET\s+ROLE|SET\s+TRANSACTION|TRUNCATE\s+CLUSTER|TRUNCATE\s+TABLE|UPDATE|abs|acos|add_months|approx_count|approx_count_distinct|approx_count_distinct_agg|approx_count_distinct_detail|approx_median|approx_percentile|approx_percentile_agg|approx_percentile_detail|approx_rank|approx_sum|ascii|asciistr|asin|atan|atan2|avg|bfilename|bin_to_num|bitand|bitmap_bit_position|bitmap_bucket_number|bitmap_construct_agg|bitmap_count|bitmap_or_agg|cardinality|cast|ceil|chartorowid|chr|cluster_details|cluster_distance|cluster_id|cluster_probability|cluster_set|coalesce|collation|collect|compose|con_dbid_to_id|con_guid_to_id|con_name_to_id|con_uid_to_id|concat|convert|corr|cos|cosh|count|covar_pop|covar_samp|cube_table|cume_dist|current_date|current_timestamp|cv|dataobj_to_mat_partition|dataobj_to_partition|dbtimezone|decode|decompose|dense_rank|depth|deref|dump|existsnode|exp|extractvalue|feature_compare|feature_details|feature_id|feature_set|feature_value|first|first_value|floor|from_tz|greatest|group_id|grouping|grouping_id|hextoraw|initcap|instr|iteration_number|json_array|json_arrayagg|json_dataguide|json_mergepatch|json_object|json_objectagg|json_query|json_serialize|json_table|json_value|lag|last|last_day|last_value|lead|least|length|listagg|ln|lnnvl|localtimestamp|log|lower|lpad|ltrim|make_ref|max|median|min|mod|months_between|nanvl|nchr|new_time|next_day|nls_charset_decl_len|nls_charset_id|nls_charset_name|nls_collation_id|nls_collation_name|nls_initcap|nls_lower|nls_upper|nlssort|nth_value|ntile|nullif|numtodsinterval|numtoyminterval|nvl|nvl2|ora_dm_partition_name|ora_dst_affected|ora_dst_convert|ora_dst_error|ora_hash|ora_invoking_user|ora_invoking_userid|path|percent_rank|percentile_cont|percentile_disc|power|powermultiset|powermultiset_by_cardinality|prediction|prediction_bounds|prediction_cost|prediction_details|prediction_probability|prediction_set|presentnnv|presentv|previous|rank|ratio_to_report|rawtohex|rawtonhex|ref|reftohex|regexp_count|regexp_instr|regexp_replace|regexp_substr|remainder|replace|row_number|rowidtochar|rowidtonchar|rpad|rtrim|scn_to_timestamp|sessiontimezone|set|sign|sin|sinh|soundex|sqrt|standard_hash|stats_binomial_test|stats_crosstab|stats_f_test|stats_ks_test|stats_mode|stats_mw_test|stats_one_way_anova|stats_wsr_test|stddev|stddev_pop|stddev_samp|substr|sum|sys_connect_by_path|sys_context|sys_dburigen|sys_extract_utc|sys_guid|sys_op_zone_id|sys_typeid|sys_xmlagg|sys_xmlgen|sysdate|systimestamp|tan|tanh|timestamp_to_scn|to_approx_count_distinct|to_approx_percentile|to_binary_double|to_binary_float|to_date|to_dsinterval|to_lob|to_multi_byte|to_nclob|to_number|to_single_byte|to_timestamp|to_timestamp_tz|to_utc_timestamp_tz|to_yminterval|translate|treat|trim|tz_offset|uid|unistr|upper|user|userenv|validate_conversion|value|var_pop|var_samp|variance|vsize|width_bucket|xmlagg|xmlcast|xmlcdata|xmlcolattval|xmlcomment|xmlconcat|xmldiff|xmlelement|xmlexists|xmlforest|xmlisvalid|xmlparse|xmlpatch|xmlpi|xmlquery|xmlroot|xmlsequence|xmlserialize|xmltable|xmltransform)/,
	'CREATE-TABLESPACE.html': /(CREATE(?:\s+BIGFILE|\s+SMALLFILE)?(?:\s+LOCAL\s+TEMPORARY|\s+TEMPORARY|\s+UNDO)?\s+TABLESPACE)/,
	'Data-Types.html': /(BFILE|BINARY_DOUBLE|BINARY_FLOAT|BLOB|CHAR|CLOB|DATE|INTERVAL\s+DAY|INTERVAL\s+YEAR|LONG\s+RAW|LONG|NCHAR|NCLOB|NUMBER|NVARCHAR2|RAW|ROWID|TIMESTAMP|UROWID|VARCHAR2)/,
	'CORR_A.html': /(corr_k|corr_s)/,
	'EMPTY_BLOB-EMPTY_CLOB.html': /(empty_blob|empty_clob)/,
	'$1-datetime.html': /(extract)/,
	'REGR_-Linear-Regression-Functions.html': /(regr_(?:slope|intercept|count|r2|avgx|avgy|sxx|syy|sxy))/,
	'$1-number.html': /(round|trunc)/,
	'STATS_T_TEST_.html': /(stats_t_test_indep|stats_t_test_indepu|stats_t_test_one|stats_t_test_paired)/,
	'$1-character.html': /(to_char|to_clob|to_nchar)/,
	'Logical-Conditions.html': /(AND|NOT|OR)/,
	'$1-Condition.html': /(BETWEEN|EXISTS|IN)/,
	'Pattern-matching-Conditions.html': /(LIKE|LIKE2|LIKE4|LIKEC|REGEXP_LIKE)/,
	'Null-Conditions.html': /(IS\s+(?:NOT\s+)?NULL)/,
	'$1-Expressions.html': /(CASE)/,
	'The-UNION-ALL-INTERSECT-MINUS-Operators.html': /(UNION(?:\s+ALL)?|INTERSECT|MINUS)/,
	'Joins.html': /((?:NATURAL\s+)?(?:INNER\s+|CROSS\s+|LEFT\s+|RIGHT\s+|FULL\s+)?(?:OUTER\s+)?JOIN)/,
	'SELECT.html': /(FROM|GROUP\s+BY|HAVING|WHERE)/,
	'Sorting-Query-Results.html': /(ORDER\s+BY)/,
	'Hierarchical-Queries.html': /(CONNECT\s+BY|START\s+WITH)/,
	'Hierarchical-Query-Operators.html': /(CONNECT_BY_ROOT|PRIOR)/,
	'': /(ACCESS|ADD|ALL|ALTER|ANY|AS|ASC|BY|CHECK|CLUSTER|COLUMN|COLUMN_VALUE|COMPRESS|CONNECT|CREATE|CURRENT|DECIMAL|DEFAULT|DESC|DISTINCT|DROP|ELSE|END|EXCLUSIVE|FETCH|FILE|FLOAT|FOR|GROUP|IDENTIFIED|IMMEDIATE|INCREMENT|INDEX|INITIAL|INTEGER|INTO|IS|LEVEL|LOCK|MAXEXTENTS|MLSLABEL|MODE|MODIFY|NESTED_TABLE_ID|NOCOMPRESS|NOWAIT|NULL|NULLS|OF|OFFLINE|OFFSET|ON|ONLINE|OPTION|ORDER|PCTFREE|PUBLIC|RESOURCE|ROW|ROWNUM|ROWS|SESSION|SHARE|SIZE|SMALLINT|START|SUCCESSFUL|SYNONYM|TABLE|THEN|TO|TRIGGER|UNIQUE|USING|VALIDATE|VALUES|VARCHAR|VIEW|WHEN|WHENEVER)/,
}); // collisions: IDENTITY, extract, round, to_char, to_nchar, translate, trunc
