jush.tr.mssql = { sqlite_apo: /'/, sqlite_quo: /"/, one: /--/, com: /\/\*/, mssql_bra: /\[/, num: jush.num }; // QUOTED IDENTIFIER = OFF
jush.tr.mssql_bra = { _0: /]]/, _1: /]/ };

jush.autocompleting.sql.push('mssql', 'mssql_bra', 'sqlite_quo'); // mssql_bra and sqlite_quo are quoted identifiers

jush.slugs.mssql = name => name.toLowerCase().replace(/[\s_]+/g, '-'); // CREATE TABLE -> create-table, sql_variant -> sql-variant

jush.build_links2('mssql', 'https://learn.microsoft.com/sql/$key', /(\b)/, /(\b)/gi, {
	't-sql/statements/add-signature-transact-sql': /(ADD(?:\s+COUNTER)?\s+SIGNATURE)/,
	't-sql/language-elements/$1-transact-sql': /(ALL|AND|ANY|BETWEEN|BREAK|CASE|CHECKPOINT|CLOSE|DEALLOCATE|DECLARE\s+CURSOR|EXISTS|FETCH|GOTO|IN|KILL\s+QUERY\s+NOTIFICATION\s+SUBSCRIPTION|KILL\s+STATS\s+JOB|KILL|LIKE|NOT|OPEN|OR|PRINT|RETURN|ROLLBACK\s+TRANSACTION|ROLLBACK\s+WORK|SAVE\s+TRANSACTION|SHUTDOWN|USE|WAITFOR|(?:COALESCE|NULLIF|RAISERROR|RECONFIGURE)(?=\s*\(|$))/,
	't-sql/statements/$1-transact-sql': /(ALTER\s+APPLICATION\s+ROLE|ALTER\s+ASSEMBLY|ALTER\s+ASYMMETRIC\s+KEY|ALTER\s+AUTHORIZATION|ALTER\s+BROKER\s+PRIORITY|ALTER\s+CERTIFICATE|ALTER\s+CREDENTIAL|ALTER\s+CRYPTOGRAPHIC\s+PROVIDER|ALTER\s+DATABASE\s+AUDIT\s+SPECIFICATION|ALTER\s+DATABASE\s+ENCRYPTION\s+KEY|ALTER\s+DATABASE|ALTER\s+ENDPOINT|ALTER\s+EVENT\s+SESSION|ALTER\s+FULLTEXT\s+CATALOG|ALTER\s+FULLTEXT\s+INDEX|ALTER\s+FULLTEXT\s+STOPLIST|ALTER\s+FUNCTION|ALTER\s+INDEX|ALTER\s+LOGIN|ALTER\s+MASTER\s+KEY|ALTER\s+MESSAGE\s+TYPE|ALTER\s+PARTITION\s+FUNCTION|ALTER\s+PARTITION\s+SCHEME|ALTER\s+PROCEDURE|ALTER\s+QUEUE|ALTER\s+REMOTE\s+SERVICE\s+BINDING|ALTER\s+RESOURCE\s+GOVERNOR|ALTER\s+RESOURCE\s+POOL|ALTER\s+ROLE|ALTER\s+ROUTE|ALTER\s+SCHEMA|ALTER\s+SERVER\s+AUDIT\s+SPECIFICATION|ALTER\s+SERVER\s+AUDIT|ALTER\s+SERVICE\s+MASTER\s+KEY|ALTER\s+SERVICE|ALTER\s+SYMMETRIC\s+KEY|ALTER\s+TABLE|ALTER\s+TRIGGER|ALTER\s+USER|ALTER\s+VIEW|ALTER\s+WORKLOAD\s+GROUP|ALTER\s+XML\s+SCHEMA\s+COLLECTION|BACKUP\s+CERTIFICATE|BACKUP\s+MASTER\s+KEY|BACKUP\s+SERVICE\s+MASTER\s+KEY|BACKUP|BEGIN\s+CONVERSATION\s+TIMER|BULK\s+INSERT|CLOSE\s+MASTER\s+KEY|CREATE\s+AGGREGATE|CREATE\s+APPLICATION\s+ROLE|CREATE\s+ASSEMBLY|CREATE\s+ASYMMETRIC\s+KEY|CREATE\s+BROKER\s+PRIORITY|CREATE\s+CERTIFICATE|CREATE\s+CONTRACT|CREATE\s+CREDENTIAL|CREATE\s+CRYPTOGRAPHIC\s+PROVIDER|CREATE\s+DATABASE\s+AUDIT\s+SPECIFICATION|CREATE\s+DATABASE\s+ENCRYPTION\s+KEY|CREATE\s+DATABASE|CREATE\s+DEFAULT|CREATE\s+ENDPOINT|CREATE\s+EVENT\s+NOTIFICATION|CREATE\s+EVENT\s+SESSION|CREATE\s+FULLTEXT\s+CATALOG|CREATE\s+FULLTEXT\s+INDEX|CREATE\s+FULLTEXT\s+STOPLIST|CREATE\s+FUNCTION|CREATE\s+LOGIN|CREATE\s+MASTER\s+KEY|CREATE\s+MESSAGE\s+TYPE|CREATE\s+PARTITION\s+FUNCTION|CREATE\s+PARTITION\s+SCHEME|CREATE\s+PROCEDURE|CREATE\s+QUEUE|CREATE\s+REMOTE\s+SERVICE\s+BINDING|CREATE\s+RESOURCE\s+POOL|CREATE\s+ROLE|CREATE\s+ROUTE|CREATE\s+RULE|CREATE\s+SCHEMA|CREATE\s+SERVER\s+AUDIT\s+SPECIFICATION|CREATE\s+SERVER\s+AUDIT|CREATE\s+SERVICE|CREATE\s+STATISTICS|CREATE\s+SYMMETRIC\s+KEY|CREATE\s+SYNONYM|CREATE\s+TABLE|CREATE\s+TRIGGER|CREATE\s+TYPE|CREATE\s+USER|CREATE\s+VIEW|CREATE\s+WORKLOAD\s+GROUP|CREATE\s+XML\s+SCHEMA\s+COLLECTION|DELETE|DENY|DISABLE\s+TRIGGER|DROP\s+AGGREGATE|DROP\s+APPLICATION\s+ROLE|DROP\s+ASSEMBLY|DROP\s+ASYMMETRIC\s+KEY|DROP\s+BROKER\s+PRIORITY|DROP\s+CERTIFICATE|DROP\s+CONTRACT|DROP\s+CREDENTIAL|DROP\s+CRYPTOGRAPHIC\s+PROVIDER|DROP\s+DATABASE\s+AUDIT\s+SPECIFICATION|DROP\s+DATABASE\s+ENCRYPTION\s+KEY|DROP\s+DATABASE|DROP\s+DEFAULT|DROP\s+ENDPOINT|DROP\s+EVENT\s+NOTIFICATION|DROP\s+EVENT\s+SESSION|DROP\s+FULLTEXT\s+CATALOG|DROP\s+FULLTEXT\s+INDEX|DROP\s+FULLTEXT\s+STOPLIST|DROP\s+FUNCTION|DROP\s+INDEX|DROP\s+LOGIN|DROP\s+MASTER\s+KEY|DROP\s+MESSAGE\s+TYPE|DROP\s+PARTITION\s+FUNCTION|DROP\s+PARTITION\s+SCHEME|DROP\s+PROCEDURE|DROP\s+QUEUE|DROP\s+REMOTE\s+SERVICE\s+BINDING|DROP\s+RESOURCE\s+POOL|DROP\s+ROLE|DROP\s+ROUTE|DROP\s+RULE|DROP\s+SCHEMA|DROP\s+SERVER\s+AUDIT\s+SPECIFICATION|DROP\s+SERVER\s+AUDIT|DROP\s+SERVICE|DROP\s+SIGNATURE|DROP\s+STATISTICS|DROP\s+SYMMETRIC\s+KEY|DROP\s+SYNONYM|DROP\s+TABLE|DROP\s+TRIGGER|DROP\s+TYPE|DROP\s+USER|DROP\s+VIEW|DROP\s+WORKLOAD\s+GROUP|DROP\s+XML\s+SCHEMA\s+COLLECTION|ENABLE\s+TRIGGER|END\s+CONVERSATION|GET\s+CONVERSATION\s+GROUP|GRANT|INSERT|MERGE|MOVE\s+CONVERSATION|OPEN\s+MASTER\s+KEY|OPEN\s+SYMMETRIC\s+KEY|RESTORE\s+MASTER\s+KEY|RESTORE\s+SERVICE\s+MASTER\s+KEY|REVERT|REVOKE|SEND|TRUNCATE\s+TABLE|UPDATE\s+STATISTICS|(?:GET_TRANSMISSION_STATUS|RECEIVE|SETUSER)(?=\s*\(|$))/,
	't-sql/language-elements/$1-end-transact-sql': /(BEGIN)/,
	't-sql/statements/$1-conversation-transact-sql': /(BEGIN\s+DIALOG)/,
	't-sql/language-elements/begin-distributed-transaction-transact-sql': /(BEGIN\s+DISTRIBUTED\s+(?:TRANSACTION|TRAN))/,
	't-sql/language-elements/begin-transaction-transact-sql': /(BEGIN\s+(?:TRANSACTION|TRAN))/,
	't-sql/data-types/binary-and-varbinary-transact-sql': /((?:var)?binary)/,
	't-sql/data-types/$1-transact-sql': /(bit|date|datetime|datetime2|datetimeoffset|rowversion|smalldatetime|sql_variant|time|uniqueidentifier)/,
	't-sql/language-elements/try-catch-transact-sql': /(CATCH|TRY)/,
	't-sql/data-types/char-and-varchar-transact-sql': /((?:var)?char)/,
	't-sql/statements/close-symmetric-key-transact-sql': /(CLOSE\s+(?:SYMMETRIC\s+KEY|ALL\s+SYMMETRIC\s+KEYS))/,
	't-sql/statements/collations': /(COLLATE)/,
	't-sql/language-elements/commit-transaction-transact-sql': /(COMMIT(?:\s+(?:TRANSACTION|TRAN))?)/,
	'https://learn.microsoft.com/previous-versions/sql/sql-server-2008-r2/ms181708(v=sql.105)': /(COMPUTE)/,
	't-sql/language-elements/while-transact-sql': /(CONTINUE|WHILE)/,
	't-sql/data-types/decimal-and-numeric-transact-sql': /(decimal|numeric)/,
	't-sql/language-elements/$1-local-variable-transact-sql': /(DECLARE)/,
	't-sql/language-elements/else-if-else-transact-sql': /(ELSE)/,
	't-sql/language-elements/end-begin-end-transact-sql': /(END)/,
	't-sql/language-elements/set-operators-except-and-intersect-transact-sql': /(EXCEPT|INTERSECT)/,
	't-sql/language-elements/execute-transact-sql': /(EXECUTE|EXEC)/,
	't-sql/statements/execute-as-transact-sql': /((?:EXECUTE|EXEC)\s+AS)/,
	't-sql/data-types/float-and-real-transact-sql': /(float|real)/,
	't-sql/queries/select-$1-clause-transact-sql': /(FOR|INTO|ORDER\s+BY|OVER)/,
	't-sql/queries/$1-transact-sql': /(FROM|SELECT|TOP|UPDATE|UPDATETEXT|WHERE|WRITETEXT|(?:CONTAINS|FREETEXT|READTEXT)(?=\s*\(|$))/,
	't-sql/spatial-geography/spatial-types-geography': /(geography)/,
	't-sql/spatial-geometry/spatial-types-geometry-transact-sql': /(geometry)/,
	't-sql/language-elements/sql-server-utilities-statements-$1': /(GO)/,
	't-sql/queries/select-$1-transact-sql': /(GROUP\s+BY|HAVING)/,
	't-sql/data-types/$1-data-type-method-reference': /(hierarchyid)/,
	't-sql/statements/create-table-transact-sql-$1-property': /(IDENTITY)/,
	't-sql/language-elements/$1-else-transact-sql': /(IF)/,
	't-sql/data-types/int-bigint-smallint-and-tinyint-transact-sql': /((?:big|small|tiny)?int)/,
	't-sql/queries/is-null-transact-sql': /(IS(?:\s+NOT)?\s+NULL)/,
	't-sql/data-types/money-and-smallmoney-transact-sql': /((?:small)?money)/,
	't-sql/data-types/nchar-and-nvarchar-transact-sql': /(nchar|nvarchar)/,
	't-sql/data-types/ntext-text-and-image-transact-sql': /(ntext|text|image)/,
	't-sql/queries/$1-clause-transact-sql': /(OPTION|OUTPUT)/,
	't-sql/statements/$1-statements-transact-sql': /(RESTORE|SET)/,
	't-sql/language-elements/some-any-transact-sql': /(SOME|ANY)/,
	't-sql/language-elements/set-operators-$1-transact-sql': /(UNION)/,
	't-sql/functions/$1-transact-sql': /(VAR|XACT_STATE|(?:ABS|ACOS|APPLOCK_MODE|APPLOCK_TEST|APP_NAME|ASCII|ASIN|ASSEMBLYPROPERTY|ASYMKEYPROPERTY|ASYMKEY_ID|ATAN|ATN2|AVG|BINARY_CHECKSUM|CEILING|CHAR|CHARINDEX|CHECKSUM|CHECKSUM_AGG|COLUMNPROPERTY|COLUMNS_UPDATED|COL_LENGTH|COL_NAME|CONNECTIONPROPERTY|CONTEXT_INFO|COS|COT|COUNT|COUNT_BIG|CRYPT_GEN_RANDOM|CURRENT_REQUEST_ID|CURRENT_TIMESTAMP|CURRENT_USER|CURSOR_STATUS|CertProperty|Cert_ID|DATABASEPROPERTYEX|DATABASE_PRINCIPAL_ID|DATALENGTH|DATEADD|DATEDIFF|DATENAME|DATEPART|DAY|DB_ID|DB_NAME|DECRYPTBYASYMKEY|DECRYPTBYCERT|DECRYPTBYKEY|DECRYPTBYKEYAUTOASYMKEY|DECRYPTBYKEYAUTOCERT|DECRYPTBYPASSPHRASE|DEGREES|DENSE_RANK|DIFFERENCE|ENCRYPTBYASYMKEY|ENCRYPTBYCERT|ENCRYPTBYKEY|ENCRYPTBYPASSPHRASE|ERROR_LINE|ERROR_MESSAGE|ERROR_NUMBER|ERROR_PROCEDURE|ERROR_SEVERITY|ERROR_STATE|EVENTDATA|EXP|FILEGROUPPROPERTY|FILEGROUP_ID|FILEGROUP_NAME|FILEPROPERTY|FILE_ID|FILE_IDEX|FILE_NAME|FLOOR|FORMATMESSAGE|FULLTEXTCATALOGPROPERTY|FULLTEXTSERVICEPROPERTY|GETANSINULL|GETDATE|GETUTCDATE|GET_FILESTREAM_TRANSACTION_CONTEXT|GROUPING|GROUPING_ID|HASHBYTES|HAS_DBACCESS|HAS_PERMS_BY_NAME|HOST_ID|HOST_NAME|IDENT_CURRENT|IDENT_INCR|IDENT_SEED|INDEXKEY_PROPERTY|INDEXPROPERTY|INDEX_COL|ISDATE|ISNULL|ISNUMERIC|IS_MEMBER|IS_OBJECTSIGNED|IS_SRVROLEMEMBER|KEY_NAME|Key_GUID|Key_ID|LEFT|LEN|LOG|LOG10|LOGINPROPERTY|LOWER|LTRIM|MAX|MIN|MIN_ACTIVE_ROWVERSION|MONTH|NCHAR|NEWID|NEWSEQUENTIALID|NTILE|OBJECTPROPERTY|OBJECTPROPERTYEX|OBJECT_DEFINITION|OBJECT_ID|OBJECT_NAME|OBJECT_SCHEMA_NAME|OPENDATASOURCE|OPENQUERY|OPENROWSET|OPENXML|ORIGINAL_DB_NAME|ORIGINAL_LOGIN|PARSENAME|PATINDEX|PERMISSIONS|PI|POWER|PWDCOMPARE|PWDENCRYPT|QUOTENAME|RADIANS|RAND|RANK|REPLACE|REPLICATE|REVERSE|RIGHT|ROUND|ROWCOUNT_BIG|ROW_NUMBER|RTRIM|SCHEMA_ID|SCHEMA_NAME|SCOPE_IDENTITY|SERVERPROPERTY|SESSIONPROPERTY|SESSION_USER|SIGN|SIN|SOUNDEX|SPACE|SQL_VARIANT_PROPERTY|SQRT|SQUARE|STATS_DATE|STDEV|STDEVP|STR|STUFF|SUBSTRING|SUM|SUSER_ID|SUSER_NAME|SUSER_SID|SUSER_SNAME|SWITCHOFFSET|SYMKEYPROPERTY|SYSDATETIME|SYSDATETIMEOFFSET|SYSTEM_USER|SYSUTCDATETIME|SignByAsymKey|SignByCert|TAN|TODATETIMEOFFSET|TRIGGER_NESTLEVEL|TYPEPROPERTY|TYPE_ID|TYPE_NAME|UNICODE|UPPER|USER|USER_ID|USER_NAME|VARP|VerifySignedByAsymKey|VerifySignedByCert|YEAR)(?=\s*\(|$))/,
	't-sql/queries/$1-common-table-expression-transact-sql': /(WITH)/,
	't-sql/xml/$1': /(WITH\s+XMLNAMESPACES|(?:xml_schema_namespace)(?=\s*\(|$))/,
	't-sql/statements/create-index-transact-sql': /(CREATE(?:\s+UNIQUE)?\s+INDEX)/,
	't-sql/data-types/$1-data-type': /(json|vector)/,
	't-sql/functions/cast-and-convert-transact-sql': /(CAST|CONVERT)(?=\s*\(|$)/,
	't-sql/functions/collation-functions-$1-transact-sql': /(COLLATIONPROPERTY|TERTIARY_WEIGHTS)(?=\s*\(|$)/,
	'relational-databases/system-functions/$1-transact-sql': /(CONTAINSTABLE|FREETEXTTABLE|PathName)(?=\s*\(|$)/,
	'https://learn.microsoft.com/previous-versions/sql/sql-server-2008-r2/ms176049(v=sql.105)': /(DATABASEPROPERTY)(?=\s*\(|$)/,
	't-sql/database-console-commands/$1-transact-sql': /(DBCC)(?=\s*\(|$)/,
	't-sql/functions/replication-functions-$1': /(PUBLISHINGSERVERNAME)(?=\s*\(|$)/,
	't-sql/functions/text-and-image-functions-$1-transact-sql': /(TEXTPTR|TEXTVALID)(?=\s*\(|$)/,
	't-sql/functions/$1-trigger-functions-transact-sql': /(UPDATE)(?=\s*\(|$)/,
	't-sql/xml/xml-transact-sql': /(xml)(?=\s*\(|$)/,
}); // collisions: IDENTITY
