jush.custom_links = {sql: {'?table=$&': /\b(tab2?)\b/g}};
jush.custom_links.bac = jush.custom_links.sql;

var tests = {};
tests.highlight = [
	['htm', '<a href="">HTML</a> <!-- comment --> &amp;', '<span class="jush"><span class="jush-tag"><span class="jush-op">&lt;</span><a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/a" class="jush-help">a</a><span class="jush-att"><span class="jush-op"> </span><a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/a#href" class="jush-help">href</a><span class="jush-att_quo"><span class="jush-op">="</span><span class="jush-op">"</span></span></span><span class="jush-op">&gt;</span></span>HTML<span class="jush-tag"><span class="jush-op">&lt;</span>/a<span class="jush-op">&gt;</span></span> <span class="jush-htm_com"><span class="jush-op">&lt;!--</span> comment <span class="jush-op">--&gt;</span></span> <span class="jush-ent"><span class="jush-op">&amp;</span>amp<span class="jush-op">;</span></span></span>'],
	['htm', '<a href="" onclick="alert(\'\');">', '<span class="jush"><span class="jush-tag"><span class="jush-op">&lt;</span><a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/a" class="jush-help">a</a><span class="jush-att"><span class="jush-op"> </span><a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/a#href" class="jush-help">href</a><span class="jush-att_quo"><span class="jush-op">="</span><span class="jush-op">"</span></span></span><span class="jush-att_js"><span class="jush-op"> </span><a href="https://developer.mozilla.org/en-US/docs/Web/API/Element/click_event" class="jush-help">onclick</a><span class="jush-op">=</span><span class="jush-att_quo"><span class="jush-op">"</span><span class="jush-js_code"><a href="https://developer.mozilla.org/en/DOM/window.alert" class="jush-help">alert</a><span class="jush-op">(</span></span><span class="jush-js_code"><span class="jush-apo"><span class="jush-op">\'</span><span class="jush-op">\'</span></span>)<span class="jush-op">;</span></span><span class="jush-op">"</span></span></span><span class="jush-op">&gt;</span></span></span>'],
	['htm', '<a href="" style="color: red;">', '<span class="jush"><span class="jush-tag"><span class="jush-op">&lt;</span><a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/a" class="jush-help">a</a><span class="jush-att"><span class="jush-op"> </span><a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/a#href" class="jush-help">href</a><span class="jush-att_quo"><span class="jush-op">="</span><span class="jush-op">"</span></span></span><span class="jush-att_css"><span class="jush-op"> </span><a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes/style" class="jush-help">style</a><span class="jush-op">=</span><span class="jush-att_quo"><span class="jush-op">"</span><span class="jush-css_val"><a href="https://developer.mozilla.org/en-US/docs/Web/CSS/color" class="jush-help">color</a><span class="jush-op">:</span> red<span class="jush-op">;</span></span><span class="jush-op">"</span></span></span><span class="jush-op">&gt;</span></span></span>'],
	['htm', '<script type="text/javascript">alert("");</script> SCRIPT', '<span class="jush"><span class="jush-tag_js"><span class="jush-op">&lt;</span><a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/script" class="jush-help">script</a><span class="jush-att"><span class="jush-op"> </span><a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/script#type" class="jush-help">type</a><span class="jush-att_quo"><span class="jush-op">="</span>text/javascript<span class="jush-op">"</span></span></span><span class="jush-js"><span class="jush-op">&gt;</span><span class="jush-js_code"><a href="https://developer.mozilla.org/en/DOM/window.alert" class="jush-help">alert</a><span class="jush-op">(</span></span><span class="jush-js_code"><span class="jush-quo"><span class="jush-op">"</span><span class="jush-op">"</span></span>)<span class="jush-op">;</span></span><span class="jush-js_code"><span class="jush-op">&lt;</span>/script<span class="jush-op">&gt;</span></span></span></span> SCRIPT</span>'],
	['htm', '<style type="text/css">a { color: red; }</style> STYLE', '<span class="jush"><span class="jush-tag_css"><span class="jush-op">&lt;</span><a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/style" class="jush-help">style</a><span class="jush-att"><span class="jush-op"> </span><a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/style#type" class="jush-help">type</a><span class="jush-att_quo"><span class="jush-op">="</span>text/css<span class="jush-op">"</span></span></span><span class="jush-css"><span class="jush-op">&gt;</span>a <span class="jush-css_pro"><span class="jush-op">{</span><span class="jush-css_val"><span class="jush-op"> </span><a href="https://developer.mozilla.org/en-US/docs/Web/CSS/color" class="jush-help">color</a><span class="jush-op">:</span> red<span class="jush-op">;</span></span> <span class="jush-op">}</span></span><span class="jush-op">&lt;</span>/style<span class="jush-op">&gt;</span></span></span> STYLE</span>'],
	['htm', '<a href=index.php title=\'Quoting\'>', '<span class="jush"><span class="jush-tag"><span class="jush-op">&lt;</span><a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/a" class="jush-help">a</a><span class="jush-att"><span class="jush-op"> </span><a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/a#href" class="jush-help">href</a><span class="jush-att_val"><span class="jush-op">=</span>index.php</span></span><span class="jush-att"><span class="jush-op"> </span><a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes/title" class="jush-help">title</a><span class="jush-att_apo"><span class="jush-op">=\'</span>Quoting<span class="jush-op">\'</span></span></span><span class="jush-op">&gt;</span></span></span>'],
	['htm', '<meta http-equiv="Content-Type" content="text/html; charset=utf-8">', '<span class="jush"><span class="jush-tag"><span class="jush-op">&lt;</span><a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/meta" class="jush-help">meta</a><span class="jush-att_http"><span class="jush-op"> </span><a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/meta#http-equiv" class="jush-help">http-equiv</a><span class="jush-op">=</span><span class="jush-att_quo"><span class="jush-op">"</span><a href="https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.17" class="jush-help">Content-Type</a><span class="jush-op">"</span></span></span><span class="jush-att"><span class="jush-op"> </span><a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/meta#content" class="jush-help">content</a><span class="jush-att_quo"><span class="jush-op">="</span>text/html; charset=utf-8<span class="jush-op">"</span></span></span><span class="jush-op">&gt;</span></span></span>'],

	['tag', 'title=""', '<span class="jush"><span class="jush-att"><a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes/title" class="jush-help">title</a><span class="jush-att_quo"><span class="jush-op">="</span><span class="jush-op">"</span></span></span></span>'],

	['xml', '<rss version="0.91">', '<span class="jush"><span class="jush-xml_tag"><span class="jush-op">&lt;</span>rss<span class="jush-xml_att"><span class="jush-op"> </span>version<span class="jush-att_quo"><span class="jush-op">="</span>0.91<span class="jush-op">"</span></span></span><span class="jush-op">&gt;</span></span></span>'],

	['css', 'a { color: red } /* </style> comment */ b { font-weight: bold; color: black; }', '<span class="jush">a <span class="jush-css_pro"><span class="jush-op">{</span><span class="jush-css_val"><span class="jush-op"> </span><a href="https://developer.mozilla.org/en-US/docs/Web/CSS/color" class="jush-help">color</a><span class="jush-op">:</span> red <span class="jush-op">}</span></span></span> <span class="jush-com"><span class="jush-op">/*</span> &lt;/style&gt; comment <span class="jush-op">*/</span></span> b <span class="jush-css_pro"><span class="jush-op">{</span><span class="jush-css_val"><span class="jush-op"> </span><a href="https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight" class="jush-help">font-weight</a><span class="jush-op">:</span> bold<span class="jush-op">;</span></span><span class="jush-css_val"><span class="jush-op"> </span><a href="https://developer.mozilla.org/en-US/docs/Web/CSS/color" class="jush-help">color</a><span class="jush-op">:</span> black<span class="jush-op">;</span></span> <span class="jush-op">}</span></span></span>'],

	['js', 'if (/.+@.+/.test(email)) { /* </script> */ alert(email); }', '<span class="jush"><span class="jush-js_code"><a href="https://developer.mozilla.org/en/JavaScript/Reference/Statements/if...else" class="jush-help">if</a> <span class="jush-op">(</span></span><span class="jush-js_reg"><span class="jush-op">/</span>.+@.+<span class="jush-op">/</span></span><span class="jush-js_code">.<a href="https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/RegExp/test" class="jush-help">test</a><span class="jush-op">(</span></span><span class="jush-js_code">email)) <span class="jush-js"><span class="jush-op">{</span><span class="jush-js_code"> <span class="jush-com"><span class="jush-op">/*</span> &lt;/script&gt; <span class="jush-op">*/</span></span> <a href="https://developer.mozilla.org/en/DOM/window.alert" class="jush-help">alert</a><span class="jush-op">(</span></span><span class="jush-js_code">email)<span class="jush-op">;</span></span><span class="jush-js_code"> <span class="jush-op">}</span></span></span></span></span>'],
	['js', '/[/\\]]/.test("/");', '<span class="jush"><span class="jush-js_reg"><span class="jush-op">/</span><span class="jush-js_reg_bra"><span class="jush-op">[</span>/<span class="jush-esc"><span class="jush-op">\\</span><span class="jush-op">]</span></span><span class="jush-op">]</span></span><span class="jush-op">/</span></span><span class="jush-js_code">.<a href="https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/RegExp/test" class="jush-help">test</a><span class="jush-op">(</span></span><span class="jush-js_code"><span class="jush-quo"><span class="jush-op">"</span>/<span class="jush-op">"</span></span>)<span class="jush-op">;</span></span></span>'],
	['js', 'var s = `a ${x} b`; // comment', '<span class="jush"><span class="jush-js_code"><a href="https://developer.mozilla.org/en/JavaScript/Reference/Statements/var" class="jush-help">var</a> s <span class="jush-op">=</span></span><span class="jush-js_code"> <span class="jush-js_bac"><span class="jush-op">`</span>a <span class="jush-js"><span class="jush-op">${</span><span class="jush-js_code">x<span class="jush-op">}</span></span></span> b<span class="jush-op">`</span></span><span class="jush-op">;</span></span><span class="jush-js_code"> <span class="jush-js_one"><span class="jush-op">//</span> comment</span></span></span>'],
	['js', 'xhr.getResponseHeader("Content-Type");', '<span class="jush"><span class="jush-js_code">xhr<span class="jush-js_http"><span class="jush-op">.</span><a href="https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/getresponseheader" class="jush-help">getResponseHeader</a><span class="jush-op">(</span><span class="jush-js_http_code"><span class="jush-quo"><span class="jush-op">"</span><a href="https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.17" class="jush-help">Content-Type</a><span class="jush-op">"</span></span><span class="jush-op">)</span></span></span><span class="jush-op">;</span></span></span>'],
	['js', '{ a: [ 1, { "b": "c" }, 3 ], \'d\': 4 }', '<span class="jush"><span class="jush-js_obj"><span class="jush-op">{</span><span class="jush-js_key"> a</span><span class="jush-js_val"><span class="jush-op">:</span> <span class="jush-js_arr"><span class="jush-op">[</span> <span class="jush-num"><span class="jush-op">1</span></span>, <span class="jush-js_obj"><span class="jush-op">{</span><span class="jush-js_key"> <span class="jush-quo"><span class="jush-op">"</span>b<span class="jush-op">"</span></span></span><span class="jush-js_val"><span class="jush-op">:</span> <span class="jush-quo"><span class="jush-op">"</span>c<span class="jush-op">"</span></span> </span><span class="jush-op">}</span></span>, <span class="jush-num"><span class="jush-op">3</span></span> <span class="jush-op">]</span></span><span class="jush-op">,</span></span><span class="jush-js_key"> <span class="jush-apo"><span class="jush-op">\'</span>d<span class="jush-op">\'</span></span></span><span class="jush-js_val"><span class="jush-op">:</span> <span class="jush-num"><span class="jush-op">4</span></span> </span><span class="jush-op">}</span></span></span>'],

	['htm', '<?php echo "<a href=\'$href\'>";', '<span class="jush"><span class="jush-php"><span class="jush-op">&lt;?php</span><span class="jush-php2"> <span class="jush-php_echo"><a href="https://www.php.net/function.echo" class="jush-help">echo</a> <span class="jush-php_quo"><span class="jush-op">"</span><span class="jush-tag"><span class="jush-op">&lt;</span><a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/a" class="jush-help">a</a><span class="jush-att"><span class="jush-op"> </span><a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/a#href" class="jush-help">href</a><span class="jush-att_apo"><span class="jush-op">=\'</span></span></span></span><span class="jush-php_var">$href</span><span class="jush-tag"><span class="jush-att"><span class="jush-att_apo"><span class="jush-op">\'</span></span></span><span class="jush-op">&gt;</span></span><span class="jush-op">"</span></span><span class="jush-op">;</span></span></span></span></span>'],
	['htm', '<?="<a>";log()?><b>', '<span class="jush"><span class="jush-php"><span class="jush-op">&lt;?</span><span class="jush-php_echo"><span class="jush-op">=</span><span class="jush-php_quo"><span class="jush-op">"</span><span class="jush-tag"><span class="jush-op">&lt;</span><a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/a" class="jush-help">a</a><span class="jush-op">&gt;</span></span><span class="jush-op">"</span></span><span class="jush-op">;</span></span><span class="jush-php2"><a href="https://www.php.net/function.log" class="jush-help">log</a>()<span class="jush-op">?&gt;</span></span></span><span class="jush-tag"><span class="jush-op">&lt;</span><a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/b" class="jush-help">b</a><span class="jush-op">&gt;</span></span></span>'],
	['php', 'echo "Test" . $_SERVER["PHP_SELF"]; /* ?> comment */ mysql_free_result($result);', '<span class="jush"><span class="jush-php2"><span class="jush-php_echo"><a href="https://www.php.net/function.echo" class="jush-help">echo</a> <span class="jush-php_quo"><span class="jush-op">"</span>Test<span class="jush-op">"</span></span> . <span class="jush-php_var"><a href="https://www.php.net/reserved.variables.server" class="jush-help">$_SERVER</a></span>[<span class="jush-php_quo"><span class="jush-op">"</span>PHP_SELF<span class="jush-op">"</span></span>]<span class="jush-op">;</span></span> <span class="jush-php_com"><span class="jush-op">/*</span> ?&gt; comment <span class="jush-op">*/</span></span> mysql_free_result(<span class="jush-php_var">$result</span>);</span></span>'],
	['php', 'mysql_query("SELECT 1");', '<span class="jush"><span class="jush-php2"><span class="jush-php_sql"><a href="https://www.php.net/function.mysql_query" class="jush-help">mysql_query</a><span class="jush-op">(</span><span class="jush-php_quo"><span class="jush-op">"</span><span class="jush-sql_code"><a href="https://dev.mysql.com/doc/mysql/en/select.html" class="jush-help">SELECT</a> <span class="jush-num"><span class="jush-op">1</span></span></span><span class="jush-op">"</span></span><span class="jush-op">)</span></span>;</span></span>'],
	['php', '/** @return bool */ ini_set("display_errors", true);', '<span class="jush"><span class="jush-php2"><span class="jush-php_doc"><span class="jush-op">/**</span> <a href="https://manual.phpdoc.org/HTMLSmartyConverter/HandS/phpDocumentor/tutorial_tags.return.pkg.html" class="jush-help">@return</a> bool <span class="jush-op">*/</span></span> <span class="jush-php_phpini"><a href="https://www.php.net/function.ini_set" class="jush-help">ini_set</a><span class="jush-op">(</span><span class="jush-php_quo"><span class="jush-op">"</span><a href="https://www.php.net/errorfunc.configuration#ini.display-errors" class="jush-help">display_errors</a><span class="jush-op">"</span></span><span class="jush-op">,</span></span> <a href="https://www.php.net/language.types.singleton" class="jush-help">true</a>);</span></span>'],
	['php', 'header("HTTP/1.1 404 Not Found");', '<span class="jush"><span class="jush-php2"><span class="jush-php_http"><a href="https://www.php.net/function.header" class="jush-help">header</a><span class="jush-op">(</span><span class="jush-php_quo"><span class="jush-op">"</span>HTTP/1.1 <a href="https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.5" class="jush-help">404 Not Found</a><span class="jush-op">"</span></span><span class="jush-op">)</span></span>;</span></span>'],
	['php', 'header("Content-Type: text/html; charset=utf-8");', '<span class="jush"><span class="jush-php2"><span class="jush-php_http"><a href="https://www.php.net/function.header" class="jush-help">header</a><span class="jush-op">(</span><span class="jush-php_quo"><span class="jush-op">"</span><a href="https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.17" class="jush-help">Content-Type</a>: text/html; charset=utf-8<span class="jush-op">"</span></span><span class="jush-op">)</span></span>;</span></span>'],
	['php', 'mail("", "", "", "From: info@example.com\\nMIME-Version: 1.0");', '<span class="jush"><span class="jush-php2"><span class="jush-php_mail"><a href="https://www.php.net/function.mail" class="jush-help">mail</a><span class="jush-op">(</span><span class="jush-php_quo"><span class="jush-op">"</span><span class="jush-op">"</span></span>, <span class="jush-php_quo"><span class="jush-op">"</span><span class="jush-op">"</span></span>, <span class="jush-php_quo"><span class="jush-op">"</span><span class="jush-op">"</span></span>, <span class="jush-php_quo"><span class="jush-op">"</span><a href="https://tools.ietf.org/html/rfc2076#section-3.4" class="jush-help">From</a>: info@example.com<span class="jush-esc"><span class="jush-op">\\</span><span class="jush-op">n</span></span><a href="https://tools.ietf.org/html/rfc2076#section-3.3" class="jush-help">MIME-Version</a>: 1.0<span class="jush-op">"</span></span><span class="jush-op">)</span></span>;</span></span>'],
	['php', 'echo <<<EOT\ntext $x\nEOT\n. <<<\'EOT\'\ntext $x\nEOT;\necho 1;', '<span class="jush"><span class="jush-php2"><span class="jush-php_echo"><a href="https://www.php.net/function.echo" class="jush-help">echo</a> <span class="jush-php_eot"><span class="jush-op">&lt;&lt;&lt;</span><span class="jush-php_eot2"><span class="jush-op">EOT</span>\ntext <span class="jush-php_var">$x</span><span class="jush-op">\n</span>EOT</span></span>\n. <span class="jush-php_eot"><span class="jush-op">&lt;&lt;&lt;</span>\'<span class="jush-php_eot2"><span class="jush-op">EOT</span>\'\ntext $x<span class="jush-op">\n</span>EOT</span></span><span class="jush-op">;</span></span>\n<span class="jush-php_echo"><a href="https://www.php.net/function.echo" class="jush-help">echo</a> <span class="jush-num"><span class="jush-op">1</span></span><span class="jush-op">;</span></span></span></span>'],
	['php', 'echo \'apo\'; // line\n# hash\necho "a $var b";', '<span class="jush"><span class="jush-php2"><span class="jush-php_echo"><a href="https://www.php.net/function.echo" class="jush-help">echo</a> <span class="jush-php_apo"><span class="jush-op">\'</span>apo<span class="jush-op">\'</span></span><span class="jush-op">;</span></span> <span class="jush-php_one"><span class="jush-op">//</span> line<span class="jush-op">\n</span></span><span class="jush-php_one"><span class="jush-op">#</span> hash<span class="jush-op">\n</span></span><span class="jush-php_echo"><a href="https://www.php.net/function.echo" class="jush-help">echo</a> <span class="jush-php_quo"><span class="jush-op">"</span>a <span class="jush-php_var">$var</span> b<span class="jush-op">"</span></span><span class="jush-op">;</span></span></span></span>'],

	['sql', 'SELECT 1, \'MySQL\'', '<span class="jush"><span class="jush-sql_code"><a href="https://dev.mysql.com/doc/mysql/en/select.html" class="jush-help">SELECT</a> <span class="jush-num"><span class="jush-op">1</span></span>, <span class="jush-sql_apo"><span class="jush-op">\'</span>MySQL<span class="jush-op">\'</span></span></span></span>'],
	['sql', 'SELECT 1 -- comment\n# hash\n/* block */', '<span class="jush"><span class="jush-sql_code"><a href="https://dev.mysql.com/doc/mysql/en/select.html" class="jush-help">SELECT</a> <span class="jush-num"><span class="jush-op">1</span></span> <span class="jush-one"><span class="jush-op">-- </span>comment</span>\n<span class="jush-one"><span class="jush-op">#</span> hash</span>\n<span class="jush-com"><span class="jush-op">/*</span> block <span class="jush-op">*/</span></span></span></span>'],
	['sql', '/*!40101 SELECT 1 */', '<span class="jush"><span class="jush-com_code"><span class="jush-op">/*!40101</span></span><span class="jush-sql_code"> <a href="https://dev.mysql.com/doc/mysql/en/select.html" class="jush-help">SELECT</a> <span class="jush-num"><span class="jush-op">1</span></span> <span class="jush-com_code"><span class="jush-op">*/</span></span></span></span>'],
	['sql', 'SELECT `col`, @var, \'It\'\'s\'', '<span class="jush"><span class="jush-sql_code"><a href="https://dev.mysql.com/doc/mysql/en/select.html" class="jush-help">SELECT</a> <span class="jush-bac"><span class="jush-op">`</span>col<span class="jush-op">`</span></span>, <span class="jush-sql_var"><span class="jush-op">@</span>var</span>, <span class="jush-sql_apo"><span class="jush-op">\'</span>It<span class="jush-op">\'\'</span>s<span class="jush-op">\'</span></span></span></span>'],
	['sql', 'SELECT * FROM tab JOIN `tab2`', '<span class="jush"><span class="jush-sql_code"><a href="https://dev.mysql.com/doc/mysql/en/select.html" class="jush-help">SELECT</a> * <a>FROM</a> <a href="?table=tab" class="jush-custom">tab</a> <a href="https://dev.mysql.com/doc/mysql/en/join.html" class="jush-help">JOIN</a> <span class="jush-bac"><span class="jush-op">`</span><a href="?table=tab2" class="jush-custom">tab2</a><span class="jush-op">`</span></span></span></span>'],
	['sqlite', 'SELECT 1, \'SQLite\'', '<span class="jush"><a href="https://www.sqlite.org/lang_select.html" class="jush-help">SELECT</a> <span class="jush-num"><span class="jush-op">1</span></span>, <span class="jush-sqlite_apo"><span class="jush-op">\'</span>SQLite<span class="jush-op">\'</span></span></span>'],
	['sqlite', 'CREATE TABLE t (id INTEGER) STRICT, WITHOUT ROWID', '<span class="jush"><a href="https://www.sqlite.org/lang_createtable.html" class="jush-help">CREATE TABLE</a> t (id <a href="https://www.sqlite.org/datatype3.html" class="jush-help">INTEGER</a>) <a href="https://www.sqlite.org/stricttables.html" class="jush-help">STRICT</a>, <a href="https://www.sqlite.org/withoutrowid.html" class="jush-help">WITHOUT ROWID</a></span>'],
	['sqlite', 'WITH RECURSIVE cte AS (SELECT 1) SELECT * FROM cte', '<span class="jush"><a href="https://www.sqlite.org/lang_with.html" class="jush-help">WITH</a> <a>RECURSIVE</a> cte <a>AS</a> (<a href="https://www.sqlite.org/lang_select.html" class="jush-help">SELECT</a> <span class="jush-num"><span class="jush-op">1</span></span>) <a href="https://www.sqlite.org/lang_select.html" class="jush-help">SELECT</a> * <a>FROM</a> cte</span>'],
	['sqlite', 'SELECT row_number() OVER (PARTITION BY x ORDER BY y) FROM t', '<span class="jush"><a href="https://www.sqlite.org/lang_select.html" class="jush-help">SELECT</a> <a href="https://www.sqlite.org/windowfunctions.html#row_number" class="jush-help">row_number</a>() <a href="https://www.sqlite.org/windowfunctions.html" class="jush-help">OVER</a> (<a href="https://www.sqlite.org/windowfunctions.html" class="jush-help">PARTITION BY</a> x <a>ORDER</a> <a>BY</a> y) <a>FROM</a> t</span>'],
	['sqlite', 'INSERT INTO t VALUES (1) ON CONFLICT DO UPDATE SET x = excluded.x RETURNING id', '<span class="jush"><a href="https://www.sqlite.org/lang_insert.html" class="jush-help">INSERT</a> <a>INTO</a> t <a>VALUES</a> (<span class="jush-num"><span class="jush-op">1</span></span>) <a>ON</a> <a href="https://www.sqlite.org/lang_conflict.html" class="jush-help">CONFLICT</a> <a>DO</a> <a href="https://www.sqlite.org/lang_update.html" class="jush-help">UPDATE</a> <a>SET</a> x = <a>excluded</a>.x <a>RETURNING</a> id</span>'],
	['sqlite', 'SELECT json_extract(data, \'$.x\') FROM t', '<span class="jush"><a href="https://www.sqlite.org/lang_select.html" class="jush-help">SELECT</a> <a href="https://www.sqlite.org/json1.html#json_extract" class="jush-help">json_extract</a>(data, <span class="jush-sqlite_apo"><span class="jush-op">\'</span>$.x<span class="jush-op">\'</span></span>) <a>FROM</a> t</span>'],
	['sqlite', 'SELECT sqrt(4), unixepoch()', '<span class="jush"><a href="https://www.sqlite.org/lang_select.html" class="jush-help">SELECT</a> <a href="https://www.sqlite.org/lang_mathfunc.html#sqrt" class="jush-help">sqrt</a>(<span class="jush-num"><span class="jush-op">4</span></span>), <a href="https://www.sqlite.org/lang_datefunc.html#unixepoch" class="jush-help">unixepoch</a>()</span>'],
	['pgsql', 'SELECT 1, $tag$ \'text\' $tag$, /* WHERE */ \'PostgreSQL\'', '<span class="jush"><a href="https://www.postgresql.org/docs/current/static/sql-select.html" class="jush-help">SELECT</a> <span class="jush-num"><span class="jush-op">1</span></span>, <span class="jush-pgsql_eot"><span class="jush-op">$</span><span class="jush-pgsql_eot2"><span class="jush-op">tag$</span> \'text\' <span class="jush-op">$tag$</span></span></span>, <span class="jush-com_nest"><span class="jush-op">/*</span> WHERE <span class="jush-op">*/</span></span> <span class="jush-sql_apo"><span class="jush-op">\'</span>PostgreSQL<span class="jush-op">\'</span></span></span>'],
	['mssql', 'SELECT 1, \'MS SQL\'', '<span class="jush"><a href="https://msdn.microsoft.com/library/ms189499.aspx" class="jush-help">SELECT</a> <span class="jush-num"><span class="jush-op">1</span></span>, <span class="jush-sqlite_apo"><span class="jush-op">\'</span>MS SQL<span class="jush-op">\'</span></span></span>'],
	['oracle', 'SELECT 1, \'Oracle\'', '<span class="jush"><a href="https://download.oracle.com/docs/cd/B19306_01/server.102/b14200/statements_10002.htm" class="jush-help">SELECT</a> <span class="jush-num"><span class="jush-op">1</span></span>, <span class="jush-sqlite_apo"><span class="jush-op">\'</span>Oracle<span class="jush-op">\'</span></span></span>'],

	['sql', 'SET foreign_key_checks = 0', '<span class="jush"><span class="jush-sql_sqlset"><a href="https://dev.mysql.com/doc/mysql/en/set-statement.html" class="jush-help">SET</a><span class="jush-op"> </span><a href="https://dev.mysql.com/doc/mysql/en/server-system-variables.html#sysvar_foreign_key_checks" class="jush-help">foreign_key_checks</a> <span class="jush-sqlset_val"><span class="jush-op">=</span> <span class="jush-num"><span class="jush-op">0</span></span></span></span></span>'],
	['sqlstatus', 'Qcache_hits', '<span class="jush"><a href="https://dev.mysql.com/doc/mysql/en/server-status-variables.html#statvar_Qcache_hits" class="jush-help">Qcache_hits</a></span>'],

	['cnf', 'Listen 80\nphp_flag display_errors On', '<span class="jush"><a href="https://httpd.apache.org/docs/current/mod/mpm_common.html#listen" class="jush-help">Listen</a> 80<span class="jush-cnf_phpini"><span class="jush-op">\n</span><a href="https://www.php.net/configuration.changes#configuration.changes.apache" class="jush-help">php_flag</a><span class="jush-op"> </span><a href="https://www.php.net/errorfunc.configuration#ini.display-errors" class="jush-help">display_errors</a><span class="jush-cnf_phpini_val"><span class="jush-op"> </span>On</span></span></span>'],
	['http', 'HTTP/1.1 302 Found\nLocation: /', '<span class="jush">HTTP/1.1 <a href="https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.3.3" class="jush-help">302 Found</a>\n<a href="https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.30" class="jush-help">Location</a>: /</span>'],
	['phpini', 'display_errors = On\n; comment', '<span class="jush"><a href="https://www.php.net/errorfunc.configuration#ini.display-errors" class="jush-help">display_errors</a> = On\n<span class="jush-one"><span class="jush-op">;</span> comment</span></span>'],
	['txt', 'plain <?php echo 1; ?> text', '<span class="jush">plain &lt;?php echo 1; ?&gt; text</span>'],

	['simpledb', 'SELECT * FROM domain WHERE id = 1', '<span class="jush"><a href="https://docs.aws.amazon.com/AmazonSimpleDB/latest/DeveloperGuide/QuotingRulesSelect.html" class="jush-help">SELECT</a> * <a>FROM</a> domain <a href="https://docs.aws.amazon.com/AmazonSimpleDB/latest/DeveloperGuide/SimpleQueriesSelect.html" class="jush-help">WHERE</a> id = 1</span>'],
	['igdb', 'POST games; fields *;', '<span class="jush"><a href="https://api-docs.igdb.com/#endpoints" class="jush-help">POST</a> games; <a href="https://api-docs.igdb.com/#fields" class="jush-help">fields</a> *;</span>'],
];

tests.highlight_html = [
	['htm', '&lt;a<b>re</b>a <i>href</i>=""&gt;', '<span class="jush"><span class="jush-tag"><span class="jush-op">&lt;</span><a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/area" class="jush-help">a<b>re</b>a</a><span class="jush-att"><span class="jush-op"> <i></span><a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/area#href" class="jush-help">href</i></a><span class="jush-att_quo"><span class="jush-op">="</span><span class="jush-op">"</span></span></span><span class="jush-op">&gt;</span></span></span>']
];

var html = [];

for (var callback in tests) {
	for (var i = 0; i < tests[callback].length; i++) {
		var test = tests[callback][i];
		var highlighted = jush[callback](test[0], test[1]);
		if (highlighted !== test[2]) {
			console.log(highlighted.replace(/['\\]/g, '\\$&').replace(/\n/g, '\\n'));
			html.push('<b class="error">error:</b>');
		}
		html.push('<pre class="jush-' + test[0] + '">' + highlighted + '</pre>');
  }
}

document.getElementById('result').innerHTML = html.join('\n');
